### ISSUE TITLE
Judges

### ISSUE THREAD

**Issue by gallexi** [galantlex/tuftscomp#4]
Style | Judge | Invited? | Confirmed? | Contract sent? | Contract received? | Contract submitted? | Check cut?
-- | ---- | ---- | ----- | ---- | ---- | ---- | -----
SS | AS | ✅ | ✅ | ✅ | ✅ | ✅ | -----
SS | BI | ✅ | ✅ | ✅ | ---- | ---- | -----
SS | MD | ✅ | ✅ | ✅ | ---- | ---- | -----
SS | AG | ✅ | ✅ | ✅ | ✅ | ✅ | -----
SS | MS | ✅ | ✅ | ✅ | ✅ | ---- | -----
SS | ZB | ✅ | ✅ | ✅ | ✅ | ✅ | -----
LR | HR | ✅ | ✅ | ✅ | ✅ | ✅ | -----
LR | KB | ✅ | ✅ | ✅ | ✅ | ✅ | -----
LR | IM | ✅ | ✅ | ✅ | ---- | ---- | -----
LR | MU | ✅ | ✅ | ✅ | ✅ | ✅ | -----
LR | EZ | ✅ | ✅ | ✅ | ✅ | ✅ | -----
LR | SE | ✅ | ✅ | ✅ | ✅ | ---- | -----

**Comment by ijyliao** [comment]
Just received Stas' (SE) and Mark's (MS) contracts today.

**Comment by gallexi** [comment]
It all worked out! Closing issue.
